# Generated by Django 3.2.3 on 2021-06-02 19:30

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('rainfall', '0001_initial'), ('rainfall', '0002_reportevent'), ('rainfall', '0003_auto_20200617_1058'), ('rainfall', '0004_auto_20200619_1404'), ('rainfall', '0005_auto_20200623_1437'), ('rainfall', '0006_auto_20200623_2253'), ('rainfall', '0007_auto_20200623_2300'), ('rainfall', '0008_auto_20200623_2311'), ('rainfall', '0009_auto_20200717_1135'), ('rainfall', '0010_auto_20200720_1545'), ('rainfall', '0011_auto_20200720_1548'), ('rainfall', '0012_auto_20210104_1617'), ('rainfall', '0013_rainfallreport')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_label', models.CharField(max_length=255)),
                ('event_label', models.CharField(max_length=255)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarrObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='GaugeObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='RtrrObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
                'unique_together': set(),
            },
        ),
        migrations.AddConstraint(
            model_name='garrobservation',
            constraint=models.UniqueConstraint(fields=('timestamp',), name='garrobservation_uniq_timestamp_constraint'),
        ),
        migrations.AddConstraint(
            model_name='gaugeobservation',
            constraint=models.UniqueConstraint(fields=('timestamp',), name='gaugeobservation_uniq_timestamp_constraint'),
        ),
        migrations.AddConstraint(
            model_name='rtrrobservation',
            constraint=models.UniqueConstraint(fields=('timestamp',), name='rtrrobservation_uniq_timestamp_constraint'),
        ),
        migrations.AlterField(
            model_name='garrobservation',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='gaugeobservation',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rtrrobservation',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterModelOptions(
            name='garrobservation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='gaugeobservation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='rtrrobservation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='garrobservation',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='gaugeobservation',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='rtrrobservation',
            name='metadata',
        ),
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_id', models.CharField(max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gauge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.IntegerField(null=True)),
                ('ext_id', models.CharField(max_length=10, null=True)),
                ('nws_des', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(null=True)),
                ('ant_elev', models.FloatField(null=True)),
                ('elev_ft', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='rainfallevent',
            options={'ordering': ['-end_dt']},
        ),
        migrations.CreateModel(
            name='RtggObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='rtggobservation',
            constraint=models.UniqueConstraint(fields=('timestamp',), name='rtggobservation_uniq_timestamp_constraint'),
        ),
        migrations.RenameModel(
            old_name='RtggObservation',
            new_name='RtrgObservation',
        ),
        migrations.RemoveConstraint(
            model_name='rtrgobservation',
            name='rtggobservation_uniq_timestamp_constraint',
        ),
        migrations.AddConstraint(
            model_name='rtrgobservation',
            constraint=models.UniqueConstraint(fields=('timestamp',), name='rtrgobservation_uniq_timestamp_constraint'),
        ),
        migrations.AlterField(
            model_name='garrobservation',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='gaugeobservation',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='rtrgobservation',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='rtrrobservation',
            name='data',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='RainfallReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('month_start', models.DateField()),
                ('document', models.FileField(upload_to='')),
                ('events', models.ManyToManyField(to='rainfall.RainfallEvent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
