# Generated by Django 3.2.3 on 2021-06-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0001_squashed_0013_rainfallreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garr5Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('sid', models.IntegerField(db_index=True, verbose_name='Sensor ID')),
                ('val', models.FloatField(verbose_name='Rainfall (inches)')),
                ('src', models.CharField(max_length=4, verbose_name='Source')),
            ],
            options={
                'ordering': ['-ts', 'sid'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GarrRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('sid', models.IntegerField(db_index=True, verbose_name='Sensor ID')),
                ('val', models.FloatField(verbose_name='Rainfall (inches)')),
                ('src', models.CharField(max_length=4, verbose_name='Source')),
            ],
            options={
                'ordering': ['-ts', 'sid'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GaugeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('sid', models.IntegerField(db_index=True, verbose_name='Sensor ID')),
                ('val', models.FloatField(verbose_name='Rainfall (inches)')),
                ('src', models.CharField(max_length=4, verbose_name='Source')),
            ],
            options={
                'ordering': ['-ts', 'sid'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rtrg5Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('sid', models.IntegerField(db_index=True, verbose_name='Sensor ID')),
                ('val', models.FloatField(verbose_name='Rainfall (inches)')),
                ('src', models.CharField(max_length=4, verbose_name='Source')),
            ],
            options={
                'ordering': ['-ts', 'sid'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RtrgRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('sid', models.IntegerField(db_index=True, verbose_name='Sensor ID')),
                ('val', models.FloatField(verbose_name='Rainfall (inches)')),
                ('src', models.CharField(max_length=4, verbose_name='Source')),
            ],
            options={
                'ordering': ['-ts', 'sid'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RtrrRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('sid', models.IntegerField(db_index=True, verbose_name='Sensor ID')),
                ('val', models.FloatField(verbose_name='Rainfall (inches)')),
                ('src', models.CharField(max_length=4, verbose_name='Source')),
            ],
            options={
                'ordering': ['-ts', 'sid'],
                'abstract': False,
            },
        ),
    ]
