# Generated by Django 3.0.7 on 2020-06-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0002_reportevent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='garrobservation',
            unique_together={('id', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='gaugeobservation',
            unique_together={('id', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='rtrrobservation',
            unique_together={('id', 'timestamp')},
        ),
    ]
