# Generated by Django 3.2.3 on 2021-06-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0002_garr5record_garrrecord_gaugerecord_rtrg5record_rtrgrecord_rtrrrecord'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='garr5record',
            constraint=models.UniqueConstraint(fields=('ts', 'sid'), name='garr5record_uniq_record_constraint'),
        ),
        migrations.AddConstraint(
            model_name='garrrecord',
            constraint=models.UniqueConstraint(fields=('ts', 'sid'), name='garrrecord_uniq_record_constraint'),
        ),
        migrations.AddConstraint(
            model_name='gaugerecord',
            constraint=models.UniqueConstraint(fields=('ts', 'sid'), name='gaugerecord_uniq_record_constraint'),
        ),
        migrations.AddConstraint(
            model_name='rtrg5record',
            constraint=models.UniqueConstraint(fields=('ts', 'sid'), name='rtrg5record_uniq_record_constraint'),
        ),
        migrations.AddConstraint(
            model_name='rtrgrecord',
            constraint=models.UniqueConstraint(fields=('ts', 'sid'), name='rtrgrecord_uniq_record_constraint'),
        ),
        migrations.AddConstraint(
            model_name='rtrrrecord',
            constraint=models.UniqueConstraint(fields=('ts', 'sid'), name='rtrrrecord_uniq_record_constraint'),
        ),
    ]
