# Generated by Django 3.2.3 on 2021-06-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0003_auto_20210603_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garr5record',
            name='sid',
            field=models.CharField(db_index=True, max_length=12, verbose_name='Sensor ID'),
        ),
        migrations.AlterField(
            model_name='garrrecord',
            name='sid',
            field=models.CharField(db_index=True, max_length=12, verbose_name='Sensor ID'),
        ),
        migrations.AlterField(
            model_name='gaugerecord',
            name='sid',
            field=models.CharField(db_index=True, max_length=12, verbose_name='Sensor ID'),
        ),
        migrations.AlterField(
            model_name='rtrg5record',
            name='sid',
            field=models.CharField(db_index=True, max_length=12, verbose_name='Sensor ID'),
        ),
        migrations.AlterField(
            model_name='rtrgrecord',
            name='sid',
            field=models.CharField(db_index=True, max_length=12, verbose_name='Sensor ID'),
        ),
        migrations.AlterField(
            model_name='rtrrrecord',
            name='sid',
            field=models.CharField(db_index=True, max_length=12, verbose_name='Sensor ID'),
        ),
    ]
