# Generated by Django 3.0.7 on 2020-06-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0003_auto_20200617_1058'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='garrobservation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='gaugeobservation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rtrrobservation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='garrobservation',
            constraint=models.UniqueConstraint(fields=('timestamp',), name='garrobservation_uniq_timestamp_constraint'),
        ),
        migrations.AddConstraint(
            model_name='gaugeobservation',
            constraint=models.UniqueConstraint(fields=('timestamp',), name='gaugeobservation_uniq_timestamp_constraint'),
        ),
        migrations.AddConstraint(
            model_name='rtrrobservation',
            constraint=models.UniqueConstraint(fields=('timestamp',), name='rtrrobservation_uniq_timestamp_constraint'),
        ),
    ]
