# Generated by Django 3.0.7 on 2020-06-24 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0006_auto_20200623_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RainfallGauge',
            new_name='Gauge',
        ),
        migrations.RenameModel(
            old_name='RainfallPixel',
            new_name='Pixel',
        ),
    ]
