# Generated by Django 3.0.7 on 2020-06-24 03:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0007_auto_20200623_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gauge',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='ant_elev',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='elev_ft',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='ext_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='nws_des',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='web_id',
            field=models.IntegerField(null=True),
        ),
    ]
