# Generated by Django 3.0.8 on 2020-07-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0008_auto_20200623_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportevent',
            options={'ordering': ['-end_dt']},
        ),
    ]
