# Generated by Django 3.0.8 on 2020-07-20 19:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0009_auto_20200717_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='RtggObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='rtggobservation',
            constraint=models.UniqueConstraint(fields=('timestamp',), name='rtggobservation_uniq_timestamp_constraint'),
        ),
    ]
