# Generated by Django 3.0.8 on 2020-07-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0010_auto_20200720_1545'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RtggObservation',
            new_name='RtrgObservation',
        ),
        migrations.RemoveConstraint(
            model_name='rtrgobservation',
            name='rtggobservation_uniq_timestamp_constraint',
        ),
        migrations.AddConstraint(
            model_name='rtrgobservation',
            constraint=models.UniqueConstraint(fields=('timestamp',), name='rtrgobservation_uniq_timestamp_constraint'),
        ),
    ]
