# Generated by Django 3.1.5 on 2021-01-04 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0012_auto_20210104_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('month_start', models.DateField()),
                ('document', models.FileField(upload_to='')),
                ('events', models.ManyToManyField(to='rainfall.RainfallEvent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
