# Generated by Django 3.2 on 2021-04-13 19:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, help_text='A human-readable title describing the resource.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed multi-line description to explain the resource.')),
                ('datetime', models.DateTimeField(blank=True, verbose_name='Resource publication Date/Time')),
                ('href', models.URLField(blank=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, help_text='A human readable title describing the Collection.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed multi-line description to fully explain the Collection.')),
                ('resources', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rainways.resource')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
