# Generated by Django 3.2 on 2021-04-13 20:11

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('rainways', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rainways.resource'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(help_text='A human readable title describing the Collection.', max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='href',
            field=models.CharField(blank=True, help_text='Resource location. May be a URL or cloud resource (e.g., S3://', max_length=2048),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
