# Generated by Django 3.2 on 2021-04-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainways', '0002_auto_20210413_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='resources',
        ),
        migrations.AddField(
            model_name='collection',
            name='resources',
            field=models.ManyToManyField(blank=True, null=True, to='rainways.Resource'),
        ),
    ]
